# Список источников, откуда тянем нормативный текст.
# Можно добавлять любые URL официальных публикаций.
sources:
  - title: "Трудовой кодекс Республики Казахстан"
    url: "https://adilet.zan.kz/rus/docs/K1500000414"
  - title: "Кодекс Республики Казахстан об административных правонарушениях"
    url: "https://adilet.zan.kz/rus/docs/K1400000235"
  - title: "Гражданский процессуальный кодекс Республики Казахстан"
    url: "https://adilet.zan.kz/rus/docs/K1500000377"
  - title: "Уголовный кодекс Республики Казахстан"
    url: "https://adilet.zan.kz/rus/docs/K1400000226"
  